## Point to the Pantry output directory containing BED files:
phenotype_dir: input/phenotypes

## Give the path prefix to genotypes in plink1 (bed/bim/fam) format:
geno_prefix: ../../GTEx/geno/gtex

## Provide a list of SNP IDs to include when computing TWAS weights:
# This is optional, but it is recommended to include only SNPs present in the LD reference used later for TWAS.
twas_snps: ../../GTEx/geno/LD_SNPs.txt

## Samples to include:
samples_file: input/samples.txt

## Modalities
# List the modalities to use. The phenotype table ({modality}.bed.gz)
# must be present in the phenotype_dir, along with a
# {modality}.phenotype_groups.txt file in the case of grouped phenotypes.
modalities:
  all:
    grouped: true
  alt_polyA:
    grouped: true
  alt_TSS:
    grouped: true
  expression:
    grouped: false
  isoforms:
    grouped: true
  splicing:
    grouped: true
  stability:
    grouped: false

## Analyses
# List the analyses to run. A snakefile will be loaded for each analysis,
# steps/{analysis}.smk, and results will be written to output/{analysis}/.
# {modality} will be replaced with each modality name.
analyses:
  # heritability:
  #   files:
  #   - '{modality}.hsq.tsv'
  qtl:
    files:
    - '{modality}.cis_qtl.txt.gz'
    - '{modality}.cis_independent_qtl.txt.gz'
  # twas:
  #   files:
  #   - '{modality}.tar.bz2'
